name: Run database tests
description: Setup PHP, install dependencies, and execute Pest for a given Laravel/database combination.

inputs:
  php-version:
    description: PHP version to install.
    required: true
  laravel-version:
    description: Laravel version constraint to require.
    required: true
  db-connection:
    description: Database connection driver to use.
    required: true
  db-database:
    description: Optional database name.
    required: false
    default: ""
  db-username:
    description: Optional database username.
    required: false
    default: ""
  db-password:
    description: Optional database password.
    required: false
    default: ""
  db-collation:
    description: Optional database collation.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install SQL Server ODBC driver (linux)
      if: ${{ inputs.db-connection == 'sqlsrv' }}
      shell: bash
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo add-apt-repository https://packages.microsoft.com/ubuntu/22.04/prod
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        # Install SQL Server extensions only when needed; otherwise keep lean.
        extensions: ${{ inputs.db-connection == 'sqlsrv' && 'pdo_sqlsrv, sqlsrv, pdo' || 'pdo' }}
        coverage: none

    - uses: ramsey/composer-install@v3

    - name: Setup problem matchers
      shell: bash
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install dependencies
      shell: bash
      run: composer require "laravel/framework:${{ inputs.laravel-version }}" --no-interaction --no-update

    - name: Execute tests
      shell: bash
      env:
        INPUT_DB_CONNECTION: ${{ inputs.db-connection }}
        INPUT_DB_DATABASE: ${{ inputs.db-database }}
        INPUT_DB_USERNAME: ${{ inputs.db-username }}
        INPUT_DB_PASSWORD: ${{ inputs.db-password }}
        INPUT_DB_COLLATION: ${{ inputs.db-collation }}
      run: |
        export DB_CONNECTION="${INPUT_DB_CONNECTION}"
        [[ -n "${INPUT_DB_DATABASE}" ]] && export DB_DATABASE="${INPUT_DB_DATABASE}"
        [[ -n "${INPUT_DB_USERNAME}" ]] && export DB_USERNAME="${INPUT_DB_USERNAME}"
        [[ -n "${INPUT_DB_PASSWORD}" ]] && export DB_PASSWORD="${INPUT_DB_PASSWORD}"
        [[ -n "${INPUT_DB_COLLATION}" ]] && export DB_COLLATION="${INPUT_DB_COLLATION}"

        # SQL Server requires encrypted connections on recent images; allow the
        # self-signed cert from the container so the driver can connect.
        if [[ "${DB_CONNECTION}" == "sqlsrv" ]]; then
          export DB_ENCRYPT=true
          export DB_TRUST_SERVER_CERTIFICATE=true
        fi

        vendor/bin/pest
