name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  discussions: write
  packages: write

concurrency:
  group: release-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: buckhamduffy/release-drafter@v1
        with:
          master_branch: main
          staging_branch: staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}